### ISSUE TITLE
Installation issue when using typescript-eslint@8.0.0-alpha.39

### ISSUE THREAD

**Issue by felipe-godoi** [sweepline/eslint-plugin-unused-imports#85]
Node 20.9.0
Eslint 9.6.0

When trying to install v4.0.0 in a project containing `typescript-eslint@8.0.0-alpha.39` I'm getting the following error.
Pls help me, If you need more information I'll send it right away.

![image](https://github.com/sweepline/eslint-plugin-unused-imports/assets/36552113/bc1942d8-35e3-4f9d-88fd-3f2509f55df9)

**Comment by vandamm** [comment]
This happens to me too

**Comment by janek64** [comment]
I encountered the same issue. It seems to be caused by the `peerDependency` declaration made by this module, which enforces the version `8` for `@typescript-eslint/eslint-plugin`, which has not been published yet (only alpha tags are available).

Until the stable v8 of `typescript-eslint` is available, it should be possible to resolve this issue in your project by adding a version override to your `package.json`:
```json
  "overrides": {
    "@typescript-eslint/eslint-plugin": "^8.0.0-alpha.39"
  }
```
This works at least for my project, might be different depending on your other dependencies and configuration.
